#created by me
from django.urls import path
from .import views



urlpatterns = [
    path('basic',views.basic,name='basic'),
    path('services',views.services,name='services'),
    path('apps',views.apps,name='apps'),
    path('data',views.data,name='data'),
    path("",views.index,name='index'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('about',views.about,name='about'),
    path('location_wise',views.location_wise,name='location_wise'),
    path('netcdf_handler',views.netcdf_handler,name='netcdf_handler'),
    path('map',views.map,name='map'),
    path('sf',views.sf,name='sf'),
    path('dbTesting',views.dbTesting,name='dbTesting'),
    path('sf_db_styling',views.sf_db_styling,name='sf_db_styling'),
    path('plotting',views.plotting,name='plotting'),
    path('sf_db',views.sf_db,name='sf_db'),
    path('aSync',views.aSync,name='aSync'),
    path('bokeh',views.bokeh,name='bokeh'),
    path('timeSeriesData',views.timeSeriesData,name='timeSeriesData'),
    path('shapefile',views.shapefile,name='shapefile'),
    path('district_wise',views.district_wise,name='district_wise'),
    path('river_basin',views.river_basin,name='river_basin'),
    path('sfppt',views.sfppt,name='sfppt'),
    path('sfws',views.sfws,name='sfws'),
    path('sftemp',views.sftemp,name='sftemp'),
    path('dl',views.dl,name='dl'),
    path('pptbasin',views.pptbasin,name='pptbasin'),
    path('wsbasin',views.wsbasin,name='wsbasin'),
    path('tempbasin',views.tempbasin,name='tempbasin'),
    path('download_csv',views.download_csv,name='download_csv'),
    path('side-by-side',views.side_by_side,name='side-by-side'),
    path('side',views.side,name='side'),
    path('dl-blog',views.dl_blog,name='dl-blog'),
    path('climate-snapshot-blog',views.climate_snapshot_blog,name='climate-snapshot-blog'),
    path('ppt_view_netcdf_annual',views.ppt_view_netcdf_annual,name='ppt_view_netcdf_annual'),
    path('ppt_view_netcdf_monthly',views.ppt_view_netcdf_monthly,name='ppt_view_netcdf_monthly'),
    path('ppt_view_netcdf_daily',views.ppt_view_netcdf_daily,name='ppt_view_netcdf_daily'),
    path('ppt_view_csv_daily_district',views.ppt_view_csv_daily_district,name='ppt_view_csv_daily_district'),
    path('ppt_view_csv_monthly_district',views.ppt_view_csv_monthly_district,name='ppt_view_csv_monthly_district'),
    path('ppt_view_csv_annual_district',views.ppt_view_csv_annual_district,name='ppt_view_csv_annual_district'),
    path('ppt_view_csv_daily_state',views.ppt_view_csv_daily_state,name='ppt_view_csv_daily_state'),
    path('ppt_view_csv_monthly_state',views.ppt_view_csv_monthly_state,name='ppt_view_csv_monthly_state'),
    path('ppt_view_csv_annual_state',views.ppt_view_csv_annual_state,name='ppt_view_csv_annual_state'),
    path('ppt_view_csv_daily_basin',views.ppt_view_csv_daily_basin,name='ppt_view_csv_daily_basin'),
    path('ppt_view_csv_monthly_basin',views.ppt_view_csv_monthly_basin,name='ppt_view_csv_monthly_basin'),
    path('ppt_view_csv_annual_basin',views.ppt_view_csv_annual_basin,name='ppt_view_csv_annual_basin'),
    path('tmax_view_netcdf_annual',views.tmax_view_netcdf_annual,name='tmax_view_netcdf_annual'),
    path('tmax_view_netcdf_monthly',views.tmax_view_netcdf_monthly,name='tmax_view_netcdf_monthly'),
    path('tmax_view_netcdf_daily',views.tmax_view_netcdf_daily,name='tmax_view_netcdf_daily'),
    path('tmax_view_csv_daily_district',views.tmax_view_csv_daily_district,name='tmax_view_csv_daily_district'),
    path('tmax_view_csv_monthly_district',views.tmax_view_csv_monthly_district,name='tmax_view_csv_monthly_district'),
    path('tmax_view_csv_annual_district',views.tmax_view_csv_annual_district,name='tmax_view_csv_annual_district'),
    path('tmax_view_csv_daily_state',views.tmax_view_csv_daily_state,name='tmax_view_csv_daily_state'),
    path('tmax_view_csv_monthly_state',views.tmax_view_csv_monthly_state,name='tmax_view_csv_monthly_state'),
    path('tmax_view_csv_annual_state',views.tmax_view_csv_annual_state,name='tmax_view_csv_annual_state'),
    path('tmax_view_csv_daily_basin',views.tmax_view_csv_daily_basin,name='tmax_view_csv_daily_basin'),
    path('tmax_view_csv_monthly_basin',views.tmax_view_csv_monthly_basin,name='tmax_view_csv_monthly_basin'),
    path('tmax_view_csv_annual_basin',views.tmax_view_csv_annual_basin,name='tmax_view_csv_annual_basin'),
    path('tmin_view_netcdf_annual',views.tmin_view_netcdf_annual,name='tmin_view_netcdf_annual'),
    path('tmin_view_netcdf_monthly',views.tmin_view_netcdf_monthly,name='tmin_view_netcdf_monthly'),
    path('tmin_view_netcdf_daily',views.tmin_view_netcdf_daily,name='tmin_view_netcdf_daily'),
    path('tmin_view_csv_daily_district',views.tmin_view_csv_daily_district,name='tmin_view_csv_daily_district'),
    path('tmin_view_csv_monthly_district',views.tmin_view_csv_monthly_district,name='tmin_view_csv_monthly_district'),
    path('tmin_view_csv_annual_district',views.tmin_view_csv_annual_district,name='tmin_view_csv_annual_district'),
    path('tmin_view_csv_daily_state',views.tmin_view_csv_daily_state,name='tmin_view_csv_daily_state'),
    path('tmin_view_csv_monthly_state',views.tmin_view_csv_monthly_state,name='tmin_view_csv_monthly_state'),
    path('tmin_view_csv_annual_state',views.tmin_view_csv_annual_state,name='tmin_view_csv_annual_state'),
    path('tmin_view_csv_daily_basin',views.tmin_view_csv_daily_basin,name='tmin_view_csv_daily_basin'),
    path('tmin_view_csv_monthly_basin',views.tmin_view_csv_monthly_basin,name='tmin_view_csv_monthly_basin'),
    path('tmin_view_csv_annual_basin',views.tmin_view_csv_annual_basin,name='tmin_view_csv_annual_basin'),
    
    

]
