# Generated by Django 3.2.12 on 2024-02-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_average_daily',
            name='value',
        ),
    ]
