# Generated by Django 3.2.12 on 2024-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisapp', '0003_remove_district_average_daily_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_average_daily',
            name='value',
            field=models.IntegerField(default=20, verbose_name=20),
            preserve_default=False,
        ),
    ]
