# Generated by Django 3.2.12 on 2024-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisapp', '0004_district_average_daily_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_average_daily',
            name='value',
            field=models.IntegerField(),
        ),
    ]
