# Generated by Django 3.2.12 on 2024-08-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisapp', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
